version: "3"

services:

  weather-prometheus:
    image: ghcr.io/lambda-byte/weather-prometheus
    container_name: weather-prometheus
    ports:
      - "5025:5025"
    volumes:
      - ./config.py/:/home/weather/config.py
    restart: unless-stopped
